project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Closeread Project
      - href: BattingAvgs.qmd
        text: 2025 Batting Averages
      - href: COL-SD-2025-04-13.qmd
        text: COL @ SD - Apr 2025 series



format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

